from os import listdir, rename
from os.path import isfile, join
from string import join as jo

def read_files(folderPath):
    onlyfiles = [f for f in listdir(folderPath) if isfile(join(folderPath, f))]
    return onlyfiles

folder = r'/home/falmasri/Desktop/Tomorrowland Belgium 2016 cropped faces/5'
file_names = read_files(folder)


for idx in range(len(file_names)): #
    origin_name = file_names[idx]

    #first trial
    # file_name = origin_name[:-2]
    # char_to_replace = origin_name[-2:]
    # flipped_char = char_to_replace[::-1]
    # last_name =  "%s" %flipped_char + "%s" %file_name
    #rename(join(folder, origin_name), join(folder, new_name))

    #second trial because of error generated by first code which didn't check if the number is more than two difits
    # if origin_name[-1] == '_':
    #     new_name = origin_name[:-1]
    #     # print origin_name
    #     rename(join(folder, origin_name), join(folder, new_name))